---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shorturl
  namespace: default
  labels:
    app: shorturl
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: "AWS_ACM_ARN"
    alb.ingress.kubernetes.io/tags: Project=shorturl,team=inf
    alb.ingress.kubernetes.io/scheme: internet-facing

spec:
  rules: 
    - http:
        paths: 
        - path: /*
          backend:
            serviceName: shorturl
            servicePort: 80
