apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturl
  namespace: default
  labels:
    app: shorturl


spec:

  replicas: 3
  selector:
    matchLabels:
      app: shorturl
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate


  template:
    metadata:
      labels:
        app: shorturl
    spec:
      containers:
      - image: sigmaeibon/shorturl:latest
        name: shorturl


        envFrom:
        - configMapRef:
            name: shorturl

        ports:
          - name: node-port
            containerPort: 5000
            protocol: TCP

        resources:
          requests:
            cpu: "0.2"
            memory: "512Mi"
          limits:
            cpu: "1.0"
            memory: "1024Mi"

      restartPolicy: Always
  
