apiVersion: v1
kind: Service
metadata:
  name: shorturl
  namespace: default
  labels:
    app: shorturl
spec:
  selector:
    app: shorturl
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: NodePort